config/routes.rb
Rails.application.routes.draw do
root 'photos#index'
devise_for :users
resources :photos
resources :users
get 'user-pictures', to: 'photos#user_pictures'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_many_attached :images
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :photos
  include PgSearch
  pg_search_scope :search_by_email, against: [:email],
    using: {
      tsearch: {
        prefix: true
      }
    }  
end

app/models/welcome.rb
class Welcome < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = current_user.photos(&:images)
   end

  def user_pictures
    @user = User.find(params[:format])
    @photos = @user.photos(&:images)
  end
   
  def new
    @photo = Photo.new
  end
  
  def create
    photos = Photo.new
    
    photos.images << photos.images.attach(params[:photo][:image])
    photos.name = params["title"]["{:class=>%22form-control%22}"]
    if current_user.photos << photos
      flash[:notice] = "Successfully added new photo!"
      redirect_to photos_path
    else
     flash[:alert] = "Error adding new photo!"
     render :new
    end
  end

  def destroy
    if current_user 
      @photo = Photo.find(params[:id])
      if @photo.images.purge
        @photo.destroy
        flash[:notice] = "Successfully deleted photo"
      else 
        flash[:alert] = "Error deleteing photo"
      end
      redirect_to photos_path
    else
      flash[:alert] = "Error deleting - this is not your photo"
    end
  end
  private

  def photo_params
    params.require(:photo).permit(:name, :content, :location, images:[])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if params[:term]
      @users = User.search_by_email(params[:term])
    else
      @users = User.all
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PhotoApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">PhotoApp</a>
        
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
              <li><%= link_to "Check out other user photos", users_path %></li>
            <li><%= link_to "Upload Image", new_photo_path  %></li>
            <% if current_user %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
            <% else %>
              <li><%= link_to "Sign Up", user_registration_path, method: :post  %></>
              <li><%= link_to "Sign In", new_user_session_path  %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">

          <div class="well sidebar-nav">
           
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li><%= link_to "My Photos", photos_path %></li>
              <li><%= link_to "My Profile", user_registration_path, method: :patch  %></li>
              <li></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Morolake Merayebu 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/photos/index.html.erb
<div class="page-header"><h1>Photos</h1></div>

<div>
<% @photos.each do |photo| %>
  <div class="media-left col-md-3">
    <% photo.images.each do |image|%>
        <%= link_to(image_tag(image, width:250, height: 150), image) %>
        <%= image.record.name %>
        <div>
          <%= link_to 'delete picture', photo_path(photo), class: "btn btn-xs btn-danger",
            method: :delete, data: {confirm: "Are you sure you want to delete #{image.filename}"} %>
        </div>
    <% end %>
  </div>
  <div class="media-left col-xs-1"></div> 
  <% end %>
</div>

app/views/photos/new.html.erb
<div class="page-header"><h1>Upload Photo</h1></div>


<%= form_for @photo do |f| %>  
  <div class="form-group">
    <%= f.label :title %>
    <%= text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Upload Photo', class: 'btn btn-default' %>
    </div>
<% end %>

app/views/photos/show.html.erb
<h1 align="center"><%= 'Photo: ' + @photo.name %></h1>
<div align="center">
    <div class="row">
      <%= image_tag @photo.variant(resize: 400x400) %>
      <%# <%= image_tag @current_user.photos.url %> %>
      <span class="badge"><%= link_to 'Edit Photo Name', edit_photo_path(@photo) %></span>
    </div>
</div>

app/views/photos/user_pictures.html.erb
<div class="page-header"><h1> <%= @user.email %>'s Photos</h1></div>

<div>
<% @photos.each do |photo| %>
  <div class="media-left col-xs-3">
    <% photo.images.each do |image|%>
        <%= link_to(image_tag(image, width:250, height: 150), image) %>
        <%= image.name %>
        <div>
            <%= link_to 'delete picture', photo_path(photo), class: "btn btn-xs btn-danger",
            method: :delete, data: {confirm: "Are you sure you want to delete #{image.filename}"} %>
        </div>
    <% end %>
  </div>
  <div class="media-left col-xs-1"></div> 
  <% end %>
</div>

app/views/shared/_errors.html.erb
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@photo.errors.count, "error")} prohibited this photo from being saved:" %>
      </h2>
      <ul>
        <% @photo.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

app/views/users/index.html.erb
<div align="center">
<h3>Search for A User</h3>
<div id="stock-lookup">
  <%= form_tag users_path, method: :get do %>
    <div class="form-group row no-padding text-center col-md-9">
      <div class="col-md-10">
        <%= text_field_tag 'term', params[:term], placeholder: "Enter user's email", class: 'form-control search-box input-lg' %>
        </div>
      <div class="col-md-2">
        <%= submit_tag 'Search!', class: 'btn btn-lg btn-success' %>
        </div>
  <% end %>
</div>

  
<% @users.each do |user| %>
  <div class="well col-md-9">
    <span class="col-md-4"><%= link_to user.email, user_url(user) %></span>
    <span class="col-md-4 col-md-offset-4 btn btn-info"> <%= link_to 'Pictures', user_pictures_path(user)%></span>
  </div>

<% end %>
</div>

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>

<%if !current_user%>
<h1 class="jumbotron">Welcome To the Photo App<br/><br/>
To view your images, sign up</h1>
<% else %>
<% end %>
<br>